--- 
language: cpp

sudo: true

env: 
  global: 
    - PRETTYNAME="Fracktal Works Julia 2018 Marlin"
    - ROOT="${TRAVIS_BUILD_DIR}"
    - 

git: 
  submodules: false

branches: 
  except: gh-pages

before_install: 
  - "chmod +x ${TRAVIS_BUILD_DIR}/scripts/*"
  - "export PATH=${TRAVIS_BUILD_DIR}/scripts/:${PATH}"
  - "sleep 3"
  - "export DISPLAY=:1.0"
  - "wget --quiet https://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz"
  - "tar xf arduino-1.8.5-linux64.tar.xz"
  - "mv arduino-1.8.5 $HOME/arduino_ide"
  - "export PATH=\"$HOME/arduino_ide:$PATH\""

install:
  # Install: LiquidCrystal_I2C library
  - git clone https://github.com/kiyoshigawa/LiquidCrystal_I2C.git
  - mv LiquidCrystal_I2C/LiquidCrystal_I2C $HOME/arduino_ide/libraries/LiquidCrystal_I2C
  #
  # Install: LiquidTWI2 library
  - git clone https://github.com/lincomatic/LiquidTWI2.git
  - sudo mv LiquidTWI2 $HOME/arduino_ide/libraries/LiquidTWI2
  #
  # Install: Monochrome Graphics Library for LCDs and OLEDs
  - git clone https://github.com/olikraus/U8glib_Arduino.git
  - sudo mv U8glib_Arduino $HOME/arduino_ide/libraries/U8glib_Arduino
  #
  # Install: L6470 Stepper Motor Driver library
  # - git clone https://github.com/ameyer/Arduino-L6470.git
  # - sudo mv Arduino-L6470/L6470 $HOME/arduino_ide/libraries/L6470
  #
  # Install: TMC26X Stepper Motor Controller library
  # - git clone https://github.com/trinamic/TMC26XStepper.git
  # - sudo mv TMC26XStepper $HOME/arduino_ide/libraries/TMC26XStepper
  #
  # Install: TMC2130 Stepper Motor Controller library
  - git clone https://github.com/teemuatlut/TMC2130Stepper.git
  - sudo mv TMC2130Stepper $HOME/arduino_ide/libraries/TMC2130Stepper
  #
  # Install: TMC2208 Stepper Motor Controller library
  - git clone https://github.com/teemuatlut/TMC2208Stepper.git
  - sudo mv TMC2208Stepper $HOME/arduino_ide/libraries/TMC2208Stepper
  #
  # Install: Adafruit Neopixel library
  - git clone https://github.com/adafruit/Adafruit_NeoPixel.git
  - sudo mv Adafruit_NeoPixel $HOME/arduino_ide/libraries/Adafruit_NeoPixel

before_script: 
  - "cd ${TRAVIS_BUILD_DIR}"
  - "sed -i 's/git@github.com:/git:\\/\\/github.com\\//' .gitmodules"
  - "git submodule update --init --recursive"

script: 
  - |
    declare -a VARIANT=("JULIA_2018_GLCD" "JULIA_2018_GLCD_HB" "JULIA_2018_RPI" "JULIA_2018_RPI_E")
    # check for marlin
    if [ ! -f "$TRAVIS_BUILD_DIR/src/Marlin/Marlin/Marlin.ino" ]; then
      echo "Marlin not found"
      exit 1
    fi

    #check for source
    if [ ! -d "$TRAVIS_BUILD_DIR/src/common" ]; then
      echo "Source not found"
      exit 1
    fi

    # clear staging directory
    rm -rfv "$TRAVIS_BUILD_DIR/staging/*"
    # make staging build dir
    mkdir -p "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin"

    # copy marlin files
    cp -Rf "$TRAVIS_BUILD_DIR/src/Marlin/Marlin/*" "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/"
    # overwrite marlin files with source
    cp -Rf "$TRAVIS_BUILD_DIR/src/common/*" "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/"
    # rename marlin ino in staging build
    mv "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/Marlin.ino" "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/Julia2018Marlin.ino"

    # make build dir
    mkdir -p "$TRAVIS_BUILD_DIR/build"
    # make output dir
    mkdir -p "$TRAVIS_BUILD_DIR/output"
    # set arduino output dir
    arduino --pref build.path="$TRAVIS_BUILD_DIR/build" --board arduino:avr:mega:cpu=atmega2560 --save-prefs

    for (( i=0; i<4; i++ )); do
      # clear build directory
      rm -rfv "$TRAVIS_BUILD_DIR/build/*"
      # generate variant
      header "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin" ${i}
      # compile INO
      arduino --verify "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/Julia2018Marlin.ino"
      # check for compiled hex
      if [ -f "$TRAVIS_BUILD_DIR/build/Julia2018Marlin.ino.hex" ]; then
        cp "$TRAVIS_BUILD_DIR/build/Julia2018Marlin.ino.hex" "$TRAVIS_BUILD_DIR/output/${VARIANT[$i]}_$(date '+%Y%m%d_%H%M')_mega.hex"
      fi
    done

    ls "$TRAVIS_BUILD_DIR/output"

notifications: 
  email: 
    - on_failure: change
    - on_success: change
