--- 
language: cpp

sudo: true

env: 
  global: 
    - "PRETTYNAME=\"Fracktal Works Julia 2018 Marlin\""

git: 
  submodules: false

branches: 
  except: gh-pages

before_install: 
  - "chmod +x ${TRAVIS_BUILD_DIR}/scripts/*"
  - "export PATH=${TRAVIS_BUILD_DIR}/scripts/:${PATH}"
  - "sleep 3"
  - "export DISPLAY=:1.0"
  - "wget --quiet https://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz"
  - "tar xf arduino-1.8.5-linux64.tar.xz"
  - "mv arduino-1.8.5 $HOME/arduino_ide"
  - "export PATH=\"$HOME/arduino_ide:$PATH\""

install: 
  - "arduino --install-library \"LiquidCrystal_I2C\",\"LiquidTWI2\",\"U8glib\",\"Adafruit_NeoPixel\""

before_script: 
  - "cd ${TRAVIS_BUILD_DIR}"
  - "sed -i 's/git@github.com:/git:\\/\\/github.com\\//' .gitmodules"
  - "git submodule update --init --recursive"

script: 
  - variant

notifications: 
  email: 
    - 
      on_failure: change
    - 
      on_success: change
