#!/usr/bin/env bash
# variant

. ./scripts/constants

if [ -z "${TRAVIS}" ] 
then
  echo "Fracktal Works Marlin 1.1.9 Build Generator"
  echo " "
  echo " Parameters:"
  for i in "${!MACHINE_NAMES[@]}"; do 
    echo "  $(( $i )): ${MACHINE_NAMES[$i]}"
  done
	echo " "
fi

if [[ -z "$1" ]];	then
	exit 1
fi

if [[ $1 -lt 0 || $1 -gt 7 ]]; then
	echo "Invalid parameters"
	exit 1
fi

SHORT_VARIANT=${SHORT_VARIANTS[$1]}
MACHINE_NAME=${MACHINE_NAMES[$1]}
VARIANT=${VARIANTS[$1]}
UUID=${UUIDS[$1]}

TIMESTAMP=$(date '+%s')
DISTDATE=$(date '+%Y-%m-%d %H:%M')
DATE_STR=$(date '+%y%m%d_%H%M')
SHORT_BUILD_VERSION=$(echo "${SHORT_VARIANT}")
DETAILED_BUILD_VERSION=$(echo "${SHORT_BUILD_VERSION}_${DATE_STR}_HA")

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="${CWD}/.."
SRC="${ROOT}/src"
SRC_MARLIN="${SRC}/Marlin/Marlin"
SRC_MARLIN_INO="${SRC}/Marlin/Marlin/Marlin.ino"
SRC_COMMON="${SRC}/common"

# check for marlin
if [ ! -f "${SRC_MARLIN_INO}" ]; then
	echo "Marlin not found"
	exit 1
fi

#check for source
if [ ! -d "${SRC_COMMON}" ]; then
	echo "Source not found"
	exit 1
fi

# Directories
STAGING_NAME="${DETAILED_BUILD_VERSION}"		# staging name

STAGING="${ROOT}/staging"
STAGING_BUILD="${STAGING}/${STAGING_NAME}"
STAGING_MARLIN_INO="${STAGING_BUILD}/Marlin.ino"
STAGING_BUILD_INO="${STAGING_BUILD}/${STAGING_NAME}.ino"
BUILD="${ROOT}/build"
OUTPUT="${ROOT}/output"


# clear staging directory
rm -rfv "${STAGING}"/* &> /dev/null
# make staging build dir
mkdir -p "${STAGING_BUILD}"

# copy marlin files
cp -Rf "${SRC_MARLIN}"/* "${STAGING_BUILD}"/
# overwrite marlin files with source
cp -Rf "${SRC_COMMON}"/* "${STAGING_BUILD}"/
# rename marlin ino in staging build
mv "${STAGING_MARLIN_INO}" "${STAGING_BUILD_INO}"

# generate variant
# ./scripts/header "${STAGING_BUILD}" "$1"

# _variant <dir> <variant>
./scripts/_variant "${STAGING_BUILD}" "${VARIANT}"

# _version <dir> <timestamp> <distdate> <sbv> <dbv> <machine_name>
./scripts/_version "${STAGING_BUILD}" "${TIMESTAMP}" "${DISTDATE}" "${SHORT_BUILD_VERSION}" "${DETAILED_BUILD_VERSION}" "${MACHINE_NAME}" "${UUID}"

# _version <dir> <filename> <variant> <date_str> <distdate>
./scripts/_marlin "${STAGING_BUILD}" "${STAGING_NAME}" "${VARIANT}" "${DATE_STR}" "${DISTDATE}"

start cmd "/k node watcher.js ${STAGING_NAME}"