#!/usr/bin/env bash
# variant

declare -a VARIANT=("JULIA_2018_GLCD" "JULIA_2018_GLCD_HB" "JULIA_2018_RPI" "JULIA_2018_RPI_E" "JULIA_2018_PRO_SINGLE" "JULIA_2018_PRO_DUAL")
declare -a SHORT_VARIANT=("J18GX" "J18GB" "J18RX" "J18RE" "J18PS" "J18PD")
declare -a MACHINE_NAME=("Julia 2018 Basic" "Julia 2018 Intermediate" "Julia 2018 Advanced" "Julia 2018 Extended" "Julia 2018 Pro Single" "Julia 2018 Pro Dual")

if [ -z "${TRAVIS}" ] 
then
	echo "Fracktal Works Marlin Build Generator"
	echo " "
	echo " Parameters:"
	echo " 0: JULIA_2018_GLCD"
	echo " 1: JULIA_2018_GLCD_HB"
	echo " 2: JULIA_2018_RPI"
	echo " 3: JULIA_2018_RPI_E"
	echo " 4: JULIA_2018_PRO_SINGLE"
	echo " 5: JULIA_2018_PRO_DUAL"
	echo " "
fi

# Directories
STAGING_NAME="Julia2018Marlin"		# staging name

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="${CWD}/.."
SRC_MARLIN="${ROOT}/${STAGING_NAME}"
SRC_MARLIN_INO="${SRC_MARLIN}/${STAGING_NAME}.ino"
OUTPUT="${ROOT}/output"

# check for marlin
if [ ! -f $SRC_MARLIN_INO ]; then
	echo "Marlin not found"
	exit 1
fi

if [[ -z "$1" ]];	then
	exit 1
fi

if [[ $1 -lt 0 || $1 -gt 5 ]]; then
	echo "Invalid parameters"
	exit 1
fi

# generate variant
./scripts/header "${SRC_MARLIN}" "$1"

# Open ino file
start $SRC_MARLIN_INO