#!/usr/bin/env bash

# check for marlin
if [ ! -f "$TRAVIS_BUILD_DIR/src/Marlin/Marlin/Marlin.ino" ]; then
	echo "Marlin not found"
	exit 1
fi

#check for source
if [ ! -d "$TRAVIS_BUILD_DIR/src/common" ]; then
	echo "Source not found"
	exit 1
fi

# clear staging directory
rm -rfv "$TRAVIS_BUILD_DIR/staging/*"
# make staging build dir
mkdir -p "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin"

# copy marlin files
cp -Rf "$TRAVIS_BUILD_DIR/src/Marlin/Marlin/*" "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/"
# overwrite marlin files with source
cp -Rf "$TRAVIS_BUILD_DIR/src/common/*" "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/"
# rename marlin ino in staging build
mv "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/Marlin.ino" "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/Julia2018Marlin.ino"


# make build dir
mkdir -p "$TRAVIS_BUILD_DIR/build"
# make output dir
mkdir -p "$TRAVIS_BUILD_DIR/output"
# set arduino output dir
arduino --pref build.path="$TRAVIS_BUILD_DIR/build" --board arduino:avr:mega:cpu=atmega2560 --save-prefs

for (( i=0; i<4; i++ )); do
	# clear build directory
	rm -rfv "$TRAVIS_BUILD_DIR/build/*"
	# generate variant
	header "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin" ${i}
	# compile INO
	arduino --verify "$TRAVIS_BUILD_DIR/staging/Julia2018Marlin/Julia2018Marlin.ino"
	# check for compiled hex
	if [ -f "$TRAVIS_BUILD_DIR/build/Julia2018Marlin.ino.hex" ]; then
		cp "$TRAVIS_BUILD_DIR/build/Julia2018Marlin.ino.hex" "$TRAVIS_BUILD_DIR/output/${VARIANT[$i]}_$(date '+%Y%m%d_%H%M')_mega.hex"
	fi
done

ls "$TRAVIS_BUILD_DIR/output"
